1. Define a problem statement
Identify and clearly explain a real-world problem that can be addressed using the two
selected datasets

1. The Real-World Problem
California is highly susceptible to natural disasters, such as earthquakes and wildfires, which can render specific roads or intersections impassable. If a "critical" intersection is destroyed, it can disconnect entire communities from the rest of the state. The problem is that not all intersections are equal; some are redundant, while others are single points of failure.

We need to identify which intersections (nodes), if removed, would cause the greatest collapse in connectivity across the state.

In [8]:
import pandas as pd
import numpy as np

In [9]:
dataset = pd.read_csv(f"roadNet-CA.csv")
dataset.head(50)

    FromNodeId  ToNodeId
0            0         1
1            0         2
2            0       469
3            1         0
4            1         6
5            1       385
6            2         0
7            2         3
8          469         0
9          469       380
10         469     37415
11           6         1
12           6         5
13         385         1
14         385       384
15         385       386
16           3         2
17           3         4
18           3       419
19           3       422
20           4         3
21           4         5
22           4        98
23           4       420
24         419         3
25         419       420
26         419     35698
27         422         3
28         422       183
29         422       423
30         422     37415
31           5         4
32           5         6
33           5        98
34          98         4
35          98         5
36          98       470
37          98     35729
38         420         4
39         420       419
40         420     35709
41           7         8
42           7         9
43           7        79
44           8         7
45           8        33
46           9         7
47           9        10
48           9        84
49          79         7

In [10]:
display(dataset.describe())

         FromNodeId      ToNodeId
count  5.533214e+06  5.533214e+06
mean   9.798579e+05  9.798579e+05
std    5.678222e+05  5.678222e+05
min    0.000000e+00  0.000000e+00
25%    4.898930e+05  4.898930e+05
50%    9.779005e+05  9.779005e+05
75%    1.472587e+06  1.472587e+06
max    1.971280e+06  1.971280e+06

In [ ]:
numerical_cols = dataset.select_dtypes(include=['number'])

print("Numerical Attributes and their Data Types:")
print(numerical_cols.info())

Numerical Attributes and their Data Types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5533214 entries, 0 to 5533213
Data columns (total 2 columns):
 #   Column      Dtype
---  ------      -----
 0   FromNodeId  int64
 1   ToNodeId    int64
dtypes: int64(2)
memory usage: 84.4 MB
None

2. How the Dataset Addresses ThisUsing only roadNet-CA.csv, you can treat the road network as an unweighted graph $G = (V, E)$.Nodes ($V$): Represent every intersection and dead-end in California.Edges ($E$): Represent the physical road segments connecting them.

3. Objective of the Analysis
The goal is to perform Network Vulnerability Analysis. You want to rank nodes based on their structural importance to find the "Top 100 Most Critical Intersections."